version: '3.8'

services:
  product-query-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      - CHAT_MODEL=${CHAT_MODEL:-gpt-3.5-turbo}
      - TOP_K=${TOP_K:-3}
      - TEMPERATURE=${TEMPERATURE:-0.1}
      - MAX_TOKENS=${MAX_TOKENS:-500}
      - VECTOR_STORE_PATH=/app/data/vector_store
    volumes:
      - ./data:/app/data
    restart: unless-stopped